from typing import Protocol

from .github_actions import BackendCapabilities, BackendExecutionRef


class ExecutionBackend(Protocol):
    def capabilities(self) -> BackendCapabilities: ...
    def submit_wave(self, request: object) -> BackendExecutionRef: ...
    def get_run(self, execution: BackendExecutionRef) -> object: ...
    def cancel_run(self, execution: BackendExecutionRef) -> bool: ...
    def collect_execution_evidence(self, execution: BackendExecutionRef) -> object: ...
